#!/bin/bash
# -----------------------------------------------------------------------------
# Deutsche Telekom IT GmbH (DevSecOps Team)
# Variables file for Compliance Check - Template
# -----------------------------------------------------------------------------

# -- HOW TO USE ---------------------------------------------------------------
# 
# This file can be used to define own set of variables for compliance checks
# for Linux. To use the variables file place it in same folder as the test 
# script. 
#
# The following variables are available:
#
#     Variable        | Description 
#    -----------------|----------------------------------------------------
#    REQnn="<value>"; | Variable to enable (TRUE) or disable (FALSE) the 
#                     | testing for a specific requirement. If a requirement 
#                     | is disabled it will be marked with N/A in SoC list
#                     | generated by the test script.
#    -----------------|----------------------------------------------------
#    REMARK_REQnn=""; | Option to define a comment that will be written for
#                     | the specific requirement to the SoC list generated
#                     | by the test script.
#    ---------------------------------------------------------------------- 
#    custom variables | For some requirements additional variables can be 
#                     | configured with customer specific values. 
#    ----------------------------------------------------------------------
#
# ----------------------------------------------------------------------------

# Req-1: Example requirement
REQ1="TRUE"
REMARK_REQ1=""

        # Example for customer changeable default variable 
        # VARIABLE="xyz"


