#!/bin/bash
# -----------------------------------------------------------------------------
# Deutsche Telekom IT GmbH (DevSecOps Team)
# Variables file for Compliance Check - Linux OS for Servers (3.65)
# -----------------------------------------------------------------------------

# -- HOW TO USE ---------------------------------------------------------------
# 
# This file can be used to define own set of variables for compliance checks
# for Linux. To use the variables file place it in same folder as the test 
# script.
#
# The following variables are available:
#
#     Variable        | Description 
#    -----------------|----------------------------------------------------
#    REQnn="<value>"; | Variable to enable (TRUE) or disable (FALSE) the 
#                     | testing for a specific requirement. If a requirement 
#                     | is disabled it will be marked with N/A in SoC list
#                     | generated by the test script.
#    -----------------|----------------------------------------------------
#    REMARK_REQnn=""; | Option to define a comment that will be written for
#                     | the specific requirement to the SoC list generated
#                     | by the test script.
#    ---------------------------------------------------------------------- 
#    custom variables | For some requirements additional variables can be 
#                     | configured with customer specific values. If not 
#                     | changed the default value will be used.
#    ----------------------------------------------------------------------
#
# ----------------------------------------------------------------------------

# Req-1: Unused services and protocols must be deactivated.
REQ1="TRUE"
REMARK_REQ1=""

        # Define allowed TCP/UDP ports. Example: TCP_PORTS="22 80 443" 
        TCP_PORTS="22"
        UDP_PORTS="68 123"

# Req-2: The reachability of services must be restricted.
REQ2="TRUE"
REMARK_REQ2=""

# Req-3: Unused software must not be installed or must be uninstalled.
REQ3="TRUE"
REMARK_REQ3=""

# Req-4: Dedicated partitions must be used for growing content that can 
#        influence the availability of the system.
REQ4="TRUE"
REMARK_REQ4=""

        # Define partitions (minimum default is /tmp and /var)
        PARTITIONS="/tmp /var"

# Req-5: Parameters nodev:  nosuid and noexec must be set for partitions 
#        where this is applicable.
REQ5="TRUE"
REMARK_REQ5=""

# Req-6: Automounting must be disabled.
REQ6="TRUE"
REMARK_REQ6=""

# Req-7: The use of at/cron must be restricted to authorized users.
REQ7="TRUE"
REMARK_REQ7=""

# Req-8: Sticky bit must be set on all world-writable directories.
REQ8="TRUE"
REMARK_REQ8=""

# Req-9: No regular files that are world writable must exist.
REQ9="TRUE"
REMARK_REQ9=""

# Req-10: Passwords must be protected with an appropriate hashing function.
REQ10="TRUE"
REMARK_REQ10=""

# Req-11: The default user umask must be 027 or more restrictive.
REQ11="TRUE"
REMARK_REQ11=""

# Req-12: Not needed SUID and SGID bits must be removed from executables.
REQ12="TRUE"
REMARK_REQ12=""

# Req-13: Core dumps must be disabled.
REQ13="TRUE"
REMARK_REQ13=""

# Req-14: Protection against buffer overflows must be enabled.
REQ14="TRUE"
REMARK_REQ14=""

# Req-15: IPv4 protocol stack must be securely configured.
REQ15="TRUE"; 
REMARK_REQ15=""

# Req-16: IPv6 protocol stack must be securely configured.
REQ16="TRUE"; 
REMARK_REQ16=""

# Req-17: Emerged vulnerabilities in software and hardware of a system must 
#         be fixed or protected against misuse.
REQ17="TRUE"; 
REMARK_REQ17=""

# Req-18: GPG check for repository server must be activated and corresponding
#         keys for trustable repositories must be configured.
REQ18="TRUE"
REMARK_REQ18=""

# Req-19: User accounts must be used that allow unambiguous identification 
#         of the user.
REQ19="TRUE"
REMARK_REQ19=""

        # Define allowed local users. Example: ALLOWED_USERS="ubuntu admin"
        ALLOWED_USERS="devsecops"

# Req-20: System accounts must be non-login.
REQ20="TRUE"; 
REMARK_REQ20=""

# Req-21: User accounts must be protected against unauthorized use by at 
#         least one authentication attribute.
REQ21="TRUE"
REMARK_REQ21=""

# Req-22: User accounts with extensive rights must be protected with two 
#         authentication attributes.
REQ22="TRUE"
REMARK_REQ22=""

# Req-23: The system must be connected to a central system for user 
#         administration.
REQ23="TRUE"
REMARK_REQ23=""

# Req-24: Authentication must be used for single user mode.
REQ24="TRUE"
REMARK_REQ24=""

# Req-25: The management of the operating system must be done via a dedicated 
#         management network.
REQ25="TRUE"
REMARK_REQ25=""

# Req-26: Management services must be bound to the management network.
REQ26="TRUE"
REMARK_REQ26=""

# Req-27: Encrypted protocols must be used for management access to 
#         administrate the operating system.
REQ27="TRUE"
REMARK_REQ27=""

# Req-28: Auditing must be enabled at boot by setting a kernel parameter.
REQ28="TRUE"
REMARK_REQ28=""

# Req-29: Log rotation for logfiles must be configured.
REQ29="TRUE"
REMARK_REQ29=""

# Req-30: System time must be synchronized against a reference time source.
REQ30="TRUE"
REMARK_REQ30=""

        # Define used timezone for NTP timesynchronization
        TIMEZONE="Europe/Berlin"

# Req-31: Auditd service must be used to log security relevant events.
REQ31="TRUE"
REMARK_REQ31=""

# Req-32: System events must be logged.
REQ32="TRUE"
REMARK_REQ32=""

# Req-33: Access and Authentication events must be logged.
REQ33="TRUE"
REMARK_REQ33=""

# Req-34: Account and Group Management events must be logged.
REQ34="TRUE"
REMARK_REQ34=""

# Req-35: Configuration Change events must be logged.
REQ35="TRUE"
REMARK_REQ35=""

# Req-36: Auditd configuration must be immutable.
REQ36="TRUE"
REMARK_REQ36=""

# Req-37: Security relevant logging data must be send to an external system 
#         direct after their creation.
REQ37="TRUE"
REMARK_REQ37=""

        # Define used syslog service (rsyslog, syslog-ng)
        # Note! syslog-ng not supported in this version
        SYSLOG_TYPE="rsyslog"

# Req-38: If RSyslog is used, the default permission of 640 or more 
#         restrictive for logfiles must be configured.
REQ38="TRUE"
REMARK_REQ38=""

# Req-39: If RSyslog is used, at least one central logging server must be 
#         configured.
REQ39="TRUE"
REMARK_REQ39=""

# Req-40: If Syslog-NG is used, the default permission of 640 or more 
#         restrictive for logfiles must be configured.
REQ40="FALSE" # Note! syslog-ng not supported in this version
REMARK_REQ40="syslog-ng not used"

# Req-41: If Syslog-NG is used, at least one central logging server must be 
#         configured.
REQ41="FALSE" # Note! syslog-ng not supported in this version
REMARK_REQ41="syslog-ng not used"

# Req-42: If PAM is used, it needs to be reconfigured to use strong salted
#         password hash functions while doing many calculation rounds to protect
#         passwords.
REQ42="TRUE"
REMARK_REQ42=""

## Req-43: If PAM is used, password rules must be configured for PAM to
#         force the use of passwords with a minimum length of 12 characters
#         and a combination of three out of the following categories: upper
#         cases, lower case, numbers and special characters.
REQ43="TRUE"
REMARK_REQ43=""

# Req-44: If PAM is used, a protection against brute force and dictionary 
#         attacks that hinder password guessing must be configured in PAM.
REQ44="TRUE"
REMARK_REQ44=""

# Req-45: If PAM is used , PAM must be configured that motd did not contain 
#         any sensitive data.
REQ45="TRUE"
REMARK_REQ45=""

# Req-46: If iptables is used, policies for loopback traffic must be 
#         configured.
REQ46="TRUE"
REQ46=""

# Req-47: If iptables is used, policies for outbound and established 
#         connections must be configured.
REQ47="TRUE"
REQ47=""

# Req-48: If iptables is used, policies must exist for all ports in 
#         listening state.
REQ48="TRUE"
REQ48=""

# Req-49: If iptables is used, the default policy for tables INPUT and FORWARD
#         must be configured to drop all traffic.
REQ49="TRUE"
REQ49=""

# Req-50: If a system has Internet facing services or is a virtualization
#         host, a MAC solution must be used to restrict these services
#         respectively guest VMs.
REQ50="TRUE"
REQ50=""


# Req-51: If SELinux is used, it must not be disabled in bootloader
#         configuration.
REQ51="TRUE"
REQ51=""

# Req-52: If SELinux is used, its state must be enforced.
REQ52="TRUE"
REQ52=""

# Req-53: If SELinux is used, the policy must be configured.
REQ53="TRUE"
REMARK_REQ53=""

# Req-54: If SELinux is used, SETroubleshoot and MCS Translation Service 
#         must not be installed.
REQ54="TRUE"
REMARK_REQ54=""

# Req-55: If AppArmor is used, it must not be disabled in bootloader 
#         configuration.
REQ55="TRUE"
REMARK_REQ55=""

# Req-56: AppArmor is used, its state must be enforced.
REQ56="TRUE"
REMARK_REQ56=""

# Req-57: No legacy + entries must exist in files passwd, shadows and group.
REQ57="TRUE"
REMARK_REQ57=""

# Req-58: A user's home directory must be owned by the user and have mode 
#         750 or more restrictive.
REQ58="TRUE"
REMARK_REQ58=""

# Req-59: Default group for the root account must be GID 0.
REQ59="TRUE"
REMARK_REQ59=""

# Req-60: Root must be the only UID 0 account.
REQ60="TRUE"
REMARK_REQ60=""

# Req-61: All groups in /etc/passwd must exist in /etc/group.
REQ61="TRUE"
REMARK_EQ61=""

# Req-62: No duplicate UIDs and GIDs must exist.
REQ62="TRUE"
REMARK_REQ62=""

# Req-63: No duplicate user and group names must exist.
REQ63="TRUE"
REMARK_REQ63=""

# Req-64: The shadow group must be empty (only Debian-based Linux distributions).
REQ64="TRUE"
REMARK_REQ64=""

# Req-65: No files and directories without assigned user or group must exist.
REQ65="TRUE"
REMARK_REQ65=""

# Req-66: Permissions of security relevant configuration files must have 
#         the distribution default values or more restrictive.
REQ66="TRUE"
REMARK_REQ66=""







