---
# tel-it-security-automation :- Ansible roles for automated security hardening.  
# Copyright (c) 2020 Maximilian Hertstein [...] Deutsche Telekom AG 
# contact: devsecops@telekom.de 
# This file is distributed under the conditions of the Apache-2.0 license. 
# For details see the files LICENSING, LICENSE, and/or COPYING on the toplevel.

# ========================================================================
# Deutsch Telekom IT - DevSecOps Team
# ------------------------------------------------------------------------
# Security Hardening & Compliance Checks
# Linux OS for Servers (3.65)
#
# Tasks: 05 Mandatory Access Control
# ========================================================================

# Req-51: If SELinux is used, it must not be disabled in bootloader 
#         configuration.

- name: req-051.1 enforce selinux state in bootloader config
  lineinfile:
    state: present
    path: "/etc/default/grub"
    backrefs: yes
    regexp: '^({{ item }}=(?!.*enforcing)\"[^\"]*)(\".*)'
    line: '\1 enforcing=1\2'
  notify: update grub
  with_items:
    - GRUB_CMDLINE_LINUX
    - GRUB_CMDLINE_LINUX_DEFAULT
  when:
    - config_req_51 | default(true)
    - os_mac_solution == "selinux"
  
# Req-52: If SELinux is used, its state must be enforced.
# Req-53: If SELinux is used, the policy must be configured.

- name: req-052-053.1 configure selinux state and policy
  selinux:
    policy: "{{ selinux_policy }}"  # Req-52
    state: "{{ selinux_state }}"    # Req-53
  when: 
    - config_req_52 | default(true)
    - config_req_53 | default(true)
    - os_mac_solution == "selinux"

# Req-54: If SELinux is used, SETroubleshoot and MCS Translation Service 
#         must not be installed.

- name: req-054.1 uninstall SETroubleshoot and MCS Translation Service
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ selinux_tools }}'
  when: 
    - config_req_54 | default(true)
    - os_mac_solution == "selinux"

# Req-55: If AppArmor is used, it must not be disabled in bootloader 
#         configuration.

- name: req-055.1 enforce apparmor state in bootloader config
  lineinfile:
    state: present
    path: "/etc/default/grub"
    backrefs: yes
    regexp: '^({{ item }}=(?!.*apparmor)\"[^\"]*)(\".*)'
    line: '\1 apparmor=1\2'
  notify: update grub
  with_items:
    - GRUB_CMDLINE_LINUX
    - GRUB_CMDLINE_LINUX_DEFAULT
  when:
    - config_req_55 | default(true)
    - os_mac_solution == "apparmor"

# Req-56: AppArmor is used, its state must be enforced.

- name: req-056.1 start apparmor
  systemd:
    name: apparmor
    state: started 
    enabled: yes
  when: 
    - config_req_56 | default(true)
    - os_mac_solution == "apparmor"

- name: req-056.2 enforce apparmor state
  shell: "aa-enforce /etc/apparmor.d/{item}*"
  with_items: "{{ enforce_apparmor_files.stdout_lines | default([]) }}"
  changed_when: false
  when: 
    - config_req_56 | default(true)
    - os_mac_solution == "apparmor"



